COMPONENT=LightNodeAppC

#/tinyos/support/make
#-*-Makefile-*- vim:syntax=make
TINYOS_ROOT_DIR?=/home/wsn/tinyos-main
INCLUDES = -I/$(TINYOS_OS_DIR)/apps/tutorials/RssiDemo/
PFLAGS += -I%T/sensorboards/mda100
CFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
include $(TINYOS_ROOT_DIR)/Makefile.include
