COMPONENT=SenseAppC

#/tinyos/support/make
#-*-Makefile-*- vim:syntax=make
PFLAGS += -I%T/sensorboards/mda100

TINYOS_ROOT_DIR?=/home/wsn/tinyos-main
CFLAGS += -I$(TINYOS_OS_DIR)/lib/printf
include $(TINYOS_ROOT_DIR)/Makefile.include
